"""Actualizado tablas

Revision ID: 27a27b80f7c8
Revises: 6f302e042e1a
Create Date: 2025-05-19 06:55:12.741270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a27b80f7c8'
down_revision: Union[str, None] = '6f302e042e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edificio',
    sa.Column('edificio_id', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('mapa', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('edificio_id')
    )
    op.create_table('piso',
    sa.Column('id_piso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('edificio_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['edificio_id'], ['edificio.edificio_id'], ),
    sa.PrimaryKeyConstraint('id_piso')
    )
    op.create_table('ambiente',
    sa.Column('id_ambiente', sa.Integer(), nullable=False),
    sa.Column('nomenclatura', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.String(length=30), nullable=True),
    sa.Column('id_piso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_piso'], ['piso.id_piso'], ),
    sa.PrimaryKeyConstraint('id_ambiente')
    )
    op.create_table('ubicaciones',
    sa.Column('id_Ubicacion', sa.String(length=60), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('edificio_id', sa.String(length=20), nullable=True),
    sa.Column('id_piso', sa.Integer(), nullable=True),
    sa.Column('id_ambiente', sa.String(length=10), nullable=True),
    sa.Column('hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edificio_id'], ['edificio.edificio_id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_Ubicacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicaciones')
    op.drop_table('ambiente')
    op.drop_table('piso')
    op.drop_table('edificio')
    # ### end Alembic commands ###
