"""creada tabla Rol

Revision ID: 97d12b924a1a
Revises: 
Create Date: 2025-05-16 11:14:33.666475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d12b924a1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles2',
    sa.Column('rol_id2', sa.Integer(), nullable=False),
    sa.Column('nombre2', sa.String(length=50), nullable=True),
    sa.Column('permisos2', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rol_id2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles2')
    # ### end Alembic commands ###
